packages:
  - packages/*

saveExact: true
catalog:
  '@types/node': 26.1.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
  vitest: 4.1.9
  typescript: 7.0.2
  vite-plus: 0.2.8
  oxlint: 1.79.0
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
allowBuilds:
  esbuild: true
  unrs-resolver: true
