import { type OxlintConfig } from 'oxlint';
import type { Context } from '../lib/Context.ts';

/**
 * reference: https://github.com/fullstacksjs/eslint-config/blob/main/src/modules/base.mjs
 */
export function base(ctx: Context): OxlintConfig {
  return {
    rules: {
      'accessor-pairs': 'warn',
      'array-callback-return': 'error',
      'complexity': ['error', 14],
      'constructor-super': ctx.ts(),
      'default-case-last': 'error',
      'default-case': 'error',
      'default-param-last': 'warn',
      'eqeqeq': ['error', 'smart'],
      'for-direction': 'error',
      'func-name-matching': 'error',
      'func-names': 'error',
      'getter-return': ['error', { allowImplicit: true }],
      'guard-for-in': 'error',
      'max-depth': ['error', 4],
      'max-lines-per-function': ['warn', ctx.strictOr(100, 150)],
      'max-lines': ['error', { max: ctx.strictOr(999, 2500), skipBlankLines: false, skipComments: false }],
      'max-nested-callbacks': ['error', 3],
      'max-params': ['error', ctx.strictOr(3, 4)],
      'max-statements': 'off', // readability is controlled by `max-lines-per-function`.
      'no-alert': 'error',
      'no-array-constructor': 'error',
      'no-await-in-loop': 'error',
      'no-bitwise': 'off',
      'no-caller': 'error',
      'no-case-declarations': 'warn',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': ctx.ts(),
      'no-constant-binary-expression': 'warn',
      'no-constant-condition': 'error',
      'no-constructor-return': 'error',
      'no-debugger': 'error',
      'no-delete-var': ctx.ts(),
      'no-dupe-class-members': ctx.ts(),
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': ctx.ts(),
      'no-duplicate-imports': 'warn',
      'no-empty-function': 'off', // useless
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'warn',
      'no-empty': 'warn',
      'no-eval': 'error',
      'no-ex-assign': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': ctx.ts(),
      'no-global-assign': 'error',
      'no-implied-eval': 'error',
      'no-import-assign': ctx.ts(),
      'no-inner-declarations': 'error',
      'no-irregular-whitespace': 'error',
      'no-iterator': 'error',
      'no-lonely-if': 'warn',
      'no-loop-func': 'error',
      'no-loss-of-precision': 'error',
      'no-multi-assign': 'error',
      'no-multi-str': 'warn',
      'no-new-func': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-new-wrappers': 'error',
      'no-new': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-object-constructor': 'error',
      'no-promise-executor-return': 'off',
      'no-proto': 'error',
      'no-restricted-globals': ['error', { name: 'event', message: 'Use local parameter instead.' }],
      'no-return-assign': 'error',
      'no-script-url': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-shadow': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': ctx.ts(),
      'no-throw-literal': 'warn',
      'no-unmodified-loop-condition': 'error',
      'no-unneeded-ternary': 'warn',
      'no-unreachable': ctx.ts(),
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': ctx.ts(),
      'no-unused-private-class-members': ctx.ts(),
      'no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^ignore(d)?',
          args: 'after-used',
          ignoreRestSiblings: true,
        },
      ],
      'no-use-before-define': ctx.ts(),
      'no-useless-call': 'warn',
      'no-useless-catch': 'error',
      'no-useless-computed-key': 'warn',
      'no-useless-concat': 'warn',
      'no-useless-constructor': 'warn',
      'no-useless-escape': 'error',
      'no-useless-rename': 'warn',
      'no-useless-return': 'warn',
      'no-warning-comments': ['warn', { terms: ['fixme'], location: 'anywhere' }],
      'object-shorthand': ['error', 'properties'],
      'prefer-arrow-callback': ['warn', { allowNamedFunctions: true, allowUnboundThis: true }],
      'prefer-destructuring': ['warn', { object: true, array: false }],
      'prefer-exponentiation-operator': 'warn',
      'prefer-numeric-literals': 'error',
      'prefer-object-has-own': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'prefer-promise-reject-errors': 'warn',
      'radix': 'error',
      'require-await': 'error',
      'require-yield': 'error',
      'symbol-description': 'error',
      'use-isnan': 'error',
      'valid-typeof': ctx.ts(),
      'yoda': 'error',
      'no-async-promise-executor': 'error',
      'grouped-accessor-pairs': 'warn',
      'no-extra-boolean-cast': 'warn',
      'no-param-reassign': 'error',
      'no-plusplus': ['warn', { allowForLoopAfterthoughts: true }],
      'no-console': ctx.strict('error'),
      'preserve-caught-error': ['warn', { requireCatchParameter: true }],
      'init-declarations': ctx.strict('error'),
      'no-restricted-imports': 'off',
      'no-unused-expressions': 'error',
      'no-unexpected-multiline': 'error',
      'no-useless-assignment': 'error',
      'no-useless-backreference': 'error',

      /* Variables */
      'block-scoped-var': 'off', // we enforces block scoping with `no-var` and `prefer-const`.
      'no-implicit-globals': 'off', // we enforce block scoping with `no-var` and `prefer-const`.
      'no-lone-blocks': 'off', // we enforce block scoping with `no-var` and `prefer-const`.
      'no-var': 'error',
      'prefer-const': 'warn',
      'vars-on-top': 'error',

      /* Labels */
      'no-labels': 'error',
      'no-extra-label': 'off', // we do not allow labels `no-labels`.
      'no-label-var': 'off', // we do not allow labels `no-labels`.
      'no-unused-labels': 'off', // we do not allow labels `no-labels`.
      'no-redeclare': 'off', // we do not allow labels `no-labels`.

      /* Regular Expressions */
      'no-control-regex': 'warn',
      'no-div-regex': 'error',
      'no-invalid-regexp': 'error',
      'no-misleading-character-class': ['error', { allowEscape: true }],
      'no-regex-spaces': 'error',
      'prefer-regex-literals': ['warn', { disallowRedundantWrapping: true }],
      'no-empty-character-class': 'error',

      /* Unsupported */
      // 'no-restricted-syntax': ['error', 'WithStatement'],
      // 'no-unreachable-loop': 'error',
      // 'one-var': ['error', { uninitialized: 'never', initialized: 'never' }],
      // 'require-atomic-updates': 'warn',
    },
  };
}
