import type { OxlintConfig } from 'oxlint';
import type { Context } from '../lib/Context.ts';

const classComponent = 'off';
export function react(ctx: Context): OxlintConfig {
  return {
    plugins: ['react', 'react-perf'],
    rules: {
      'react/no-children-prop': 'warn',
      'react/no-danger-with-children': 'error',
      'react/no-direct-mutation-state': classComponent,
      'react/no-render-return-value': 'error',
      'react/no-will-update-set-state': classComponent,
      'react/jsx-key': 'error',
      'react/jsx-no-duplicate-props': 'error',
      'react/jsx-no-undef': ctx.ts(),
      'react/forward-ref-uses-ref': 'error',
      'react/require-render-return': classComponent,
      'react/rules-of-hooks': 'error',
      'react/react-in-jsx-scope': 'off',
      'react/void-dom-elements-no-children': 'error',
      'react/no-unsafe': classComponent,
      'react/exhaustive-deps': 'warn',
      'react/no-did-mount-set-state': classComponent,
      'react/no-did-update-set-state': classComponent,
      'react/no-find-dom-node': classComponent,
      'react/no-is-mounted': classComponent,
      'react/no-string-refs': classComponent,
      'react/no-unstable-nested-components': 'off',
      'react/no-object-type-as-default-prop': 'warn',
      'react/jsx-no-comment-textnodes': 'warn',
      'react/jsx-no-constructed-context-values': 'warn',
      'react/jsx-no-target-blank': 'warn',
      'react/no-danger': ctx.strict('warn'),
      'react/no-unknown-property': 'warn',
      'react/no-unescaped-entities': 'warn',
      'react/checked-requires-onchange-or-readonly': 'warn',
      'react/iframe-missing-sandbox': 'warn',
      'react/jsx-no-script-url': 'warn',
      'react/jsx-no-useless-fragment': 'warn',
      'react/no-array-index-key': 'warn',
      'react/no-multi-comp': 'off',
      'react/no-set-state': classComponent,
      'react/no-this-in-sfc': 'warn',
      'react/no-namespace': 'error',
      'react/display-name': 'warn',
      'react/hook-use-state': 'warn',
      'react/jsx-boolean-value': 'warn',
      'react/jsx-curly-brace-presence': 'warn',
      'react/jsx-fragments': 'warn',
      'react/jsx-handler-names': 'warn',
      'react/jsx-max-depth': 'off',
      'react/jsx-pascal-case': 'error',
      'react/jsx-props-no-spread-multi': 'error',
      'react/jsx-no-literals': 'off',
      'react/no-clone-element': 'warn',
      'react/no-react-children': 'warn',
      'react/no-redundant-should-component-update': classComponent,
      'react/only-export-components': [
        'warn',
        ctx.matchModule(
          'nextjs',
          {
            allowExportNames: [
              // https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config
              'experimental_ppr',
              'dynamic',
              'dynamicParams',
              'revalidate',
              'fetchCache',
              'runtime',
              'preferredRegion',
              'maxDuration',
              // https://nextjs.org/docs/app/api-reference/functions/generate-metadata
              'metadata',
              'generateMetadata',
              // https://nextjs.org/docs/app/api-reference/functions/generate-viewport
              'viewport',
              'generateViewport',
              // https://nextjs.org/docs/app/api-reference/functions/generate-image-metadata
              'generateImageMetadata',
              // https://nextjs.org/docs/app/api-reference/functions/generate-sitemaps
              'generateSitemaps',
              // https://nextjs.org/docs/app/api-reference/functions/generate-static-params
              'generateStaticParams',
            ],
          },
          { allowConstantExport: true },
        ),
      ],
      'react/prefer-es6-class': classComponent,
      'react/prefer-function-component': 'error',
      'react/self-closing-comp': 'warn',
      'react/state-in-constructor': 'warn',
      'react/style-prop-object': 'warn',
      'react/button-has-type': 'off', // buggy
      'react/forbid-component-props': 'off',
      'react/forbid-dom-props': 'off',
      'react/forbid-elements': 'off',
      'react/jsx-filename-extension': 'off',
      'react/jsx-props-no-spreading': 'off',
      'react/react-compiler': 'off',
      'react-perf/jsx-no-jsx-as-prop': 'off',
      'react-perf/jsx-no-new-array-as-prop': 'off',
      'react-perf/jsx-no-new-function-as-prop': 'off',
      'react-perf/jsx-no-new-object-as-prop': 'off',

      // Unsupported in oxlint (not in schema for v1.72.0)
      // "react/async-server-action": "warn",
      // "react/boolean-prop-naming": "off",
      // "react/default-props-match-prop-types": "off",
      // "react/destructuring-assignment": "warn",
      // "react/forbid-foreign-prop-types": "off",
      // "react/forbid-prop-types": "off",
      // "react/function-component-definition": "off",
      // "react/jsx-child-element-spacing": "off",
      // "react/jsx-closing-bracket-location": "off",
      // "react/jsx-closing-tag-location": "off",
      // "react/jsx-curly-newline": "off",
      // "react/jsx-curly-spacing": "off",
      // "react/jsx-equals-spacing": "off",
      // "react/jsx-first-prop-new-line": "off",
      // "react/jsx-indent": "off",
      // "react/jsx-indent-props": "off",
      // "react/jsx-max-props-per-line": "off",
      // "react/jsx-newline": "off",
      // "react/jsx-no-bind": "off",
      // "react/jsx-no-leaked-render": "off",
      // "react/jsx-one-expression-per-line": "off",
      // "react/jsx-props-no-multi-spaces": "off",
      // "react/jsx-sort-default-props": "off",
      // "react/jsx-sort-props": "off",
      // "react/jsx-space-before-closing": "off",
      // "react/jsx-tag-spacing": "off",
      // "react/jsx-uses-react": "error",
      // "react/jsx-uses-vars": "off",
      // "react/jsx-wrap-multilines": "off",
      // "react/no-access-state-in-setstate": "off",
      // "react/no-adjacent-inline-elements": "off",
      // "react/no-arrow-function-lifecycle": "off",
      // "react/no-deprecated": "error",
      // "react/no-invalid-html-attribute": "off",
      // "react/no-opt-in": "off",
      // "react/no-require-render": "off",
      // "react/no-typos": "off",
      // "react/no-unused-class-component-methods": "off",
      // "react/no-unused-prop-types": "off",
      // "react/no-unused-state": "off",
      // "react/prefer-exact-props": "off",
      // "react/prefer-read-only-props": "off",
      // "react/prefer-stateless-function": "off",
      // "react/prop-types": "warn",
      // "react/require-default-props": "off",
      // "react/require-optimization": "off",
      // "react/sort-comp": "off",
      // "react/sort-default-props": "off",
      // "react/sort-prop-types": "warn",
      // "react/static-property-placement": "off",
    },
  };
}
