import type { OxlintConfig } from 'oxlint';
import type { Context } from '../lib/Context.ts';

export function typescript(ctx: Context): OxlintConfig {
  return {
    plugins: ['typescript'],
    rules: {
      'typescript/adjacent-overload-signatures': 'error',
      'typescript/array-type': 'error',
      'typescript/ban-ts-comment': [
        'error',
        {
          'ts-expect-error': 'allow-with-description',
          'ts-ignore': 'allow-with-description',
          'ts-nocheck': 'allow-with-description',
          'ts-check': 'allow-with-description',
          'minimumDescriptionLength': 3,
        },
      ],
      'typescript/ban-tslint-comment': 'off',
      'typescript/class-literal-property-style': ['error', 'getters'],
      'typescript/consistent-generic-constructors': ['warn', 'constructor'],
      'typescript/consistent-indexed-object-style': 'warn',
      'typescript/consistent-type-assertions': 'error',
      'typescript/consistent-type-definitions': ['error', 'interface'],
      'typescript/consistent-type-imports': [
        'warn',
        {
          prefer: 'type-imports',
          disallowTypeAnnotations: false,
          fixStyle: 'separate-type-imports',
        },
      ],
      'typescript/explicit-function-return-type': 'off',
      'typescript/explicit-member-accessibility': 'off',
      'typescript/explicit-module-boundary-types': 'off',
      'typescript/no-confusing-non-null-assertion': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-dynamic-delete': 'error',
      'typescript/no-empty-object-type': ['warn', { allowInterfaces: 'with-single-extends' }],
      'typescript/no-explicit-any': ctx.typeAware(ctx.strict('warn')),
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-extraneous-class': ['warn', { allowWithDecorator: true }],
      'typescript/no-import-type-side-effects': 'warn',
      'typescript/no-inferrable-types': 'off',
      'typescript/no-invalid-void-type': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-nullish-coalescing': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-non-null-assertion': ctx.strictOr('warn', 'off'),
      'typescript/no-require-imports': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-type-constraint': 'warn',
      'typescript/no-unsafe-argument': ctx.typeAware(ctx.strict('warn')),
      'typescript/no-unsafe-assignment': ctx.typeAware(ctx.strict('warn')),
      'typescript/no-unsafe-call': ctx.typeAware(ctx.strict('warn')),
      'typescript/no-unsafe-declaration-merging': 'warn',
      'typescript/no-unsafe-member-access': ctx.typeAware(ctx.strict(['warn', { allowOptionalChaining: true }])),
      'typescript/no-unsafe-return': ctx.typeAware(ctx.strict('warn')),
      'typescript/no-useless-default-assignment': 'warn',
      'typescript/no-useless-empty-export': 'warn',
      'typescript/parameter-properties': 'off',
      'typescript/prefer-as-const': 'warn',
      'typescript/prefer-enum-initializers': 'off',
      'typescript/prefer-for-of': 'warn',
      'typescript/prefer-function-type': 'warn',
      'typescript/prefer-literal-enum-member': ['error', { allowBitwiseExpressions: true }],
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/prefer-readonly-parameter-types': [
        'off',
        {
          checkParameterProperties: true,
          ignoreInferredTypes: false,
          treatMethodsAsReadonly: true,
        },
      ],
      'typescript/prefer-readonly': 'off',
      'typescript/promise-function-async': 'off',
      'typescript/restrict-plus-operands': 'warn',
      'typescript/strict-boolean-expressions': 'off',

      'typescript/triple-slash-reference': 'error',
      'typescript/unified-signatures': 'error',
      ...(ctx.isTypeAware && {
        'typescript/await-thenable': 'error',
        'typescript/consistent-return': 'off',
        'typescript/consistent-type-exports': 'warn',
        'typescript/dot-notation': [
          'warn',
          {
            allowPrivateClassPropertyAccess: false,
            allowProtectedClassPropertyAccess: false,
            allowIndexSignaturePropertyAccess: true,
          },
        ],
        'typescript/no-base-to-string': 'error',
        'typescript/no-confusing-void-expression': ['off', { ignoreArrowShorthand: true, ignoreVoidOperator: true }],
        'typescript/no-duplicate-type-constituents': 'warn',
        'typescript/no-deprecated': 'error',
        'typescript/no-for-in-array': 'error',
        'typescript/no-implied-eval': 'error',
        'typescript/no-meaningless-void-operator': ['warn', { checkNever: false }],

        'typescript/no-floating-promises': ['error', { ignoreVoid: true }],
        'typescript/no-misused-promises': ['warn', { checksVoidReturn: { attributes: false } }],
        'typescript/no-misused-spread': 'error',
        'typescript/no-mixed-enums': 'error',
        'typescript/no-redundant-type-constituents': 'warn',
        'typescript/no-unnecessary-type-conversion': 'error',
        'typescript/no-unnecessary-boolean-literal-compare': 'error',
        'typescript/no-unsafe-enum-comparison': 'warn',
        'typescript/no-unsafe-function-type': 'warn',
        'typescript/no-unnecessary-condition': [
          'warn',
          {
            allowConstantLoopConditions: false,
          },
        ],
        'typescript/no-unnecessary-qualifier': 'error',
        'typescript/no-unnecessary-template-expression': 'warn',
        'typescript/no-unnecessary-type-arguments': 'error',
        'typescript/no-unnecessary-type-assertion': 'error',
        'typescript/no-unsafe-unary-minus': 'error',
        'typescript/non-nullable-type-assertion-style': 'warn',
        'typescript/only-throw-error': ['warn', { allowRethrowing: true }],
        'typescript/prefer-includes': 'warn',
        'typescript/prefer-optional-chain': 'warn',
        'typescript/prefer-reduce-type-parameter': 'warn',
        'typescript/prefer-nullish-coalescing': [
          'warn',
          {
            ignoreConditionalTests: false,
            ignoreTernaryTests: false,
            ignoreMixedLogicalExpressions: true,
          },
        ],
        'typescript/prefer-regexp-exec': 'warn',
        'typescript/prefer-promise-reject-errors': 'warn',
        'typescript/prefer-return-this-type': 'warn',
        'typescript/prefer-string-starts-ends-with': 'warn',
        'typescript/restrict-template-expressions': [
          'warn',
          {
            allowNumber: true,
            allowBoolean: false,
            allowAny: false,
            allowNullish: false,
            allowRegExp: false,
            allowNever: false,
          },
        ],
        'typescript/related-getter-setter-pairs': 'error',
        'typescript/require-array-sort-compare': ['error', { ignoreStringArrays: true }],
        'typescript/require-await': 'error',
        'typescript/return-await': 'error',
        'typescript/switch-exhaustiveness-check': 'error',
        'typescript/unbound-method': ['error', { ignoreStatic: true }],
      }),

      /* Unsupported */
      // 'typescript/camelcase': 'off',
      // 'typescript/default-param-last': 'warn',
      // 'typescript/generic-type-naming': 'off',
      // 'typescript/init-declarations': 'off',
      // 'typescript/member-naming': 'off',
      // 'typescript/member-ordering': 'off',
      // 'typescript/naming-convention': [
      // 'typescript/method-signature-style': ['warn', 'property'],
      // 'typescript/naming-convention': ['warn'],
      // 'typescript/no-array-constructor': 'error',
      // 'typescript/no-dupe-class-members': 'error',
      // 'typescript/no-empty-function': 'error',
      // 'typescript/no-invalid-this': ['error']
      // 'typescript/no-loop-func': 'error',
      // 'typescript/no-magic-numbers': ['off', { ignoreEnums: true }],
      // 'typescript/no-redeclare': ['off', { ignoreDeclarationMerge: true }],
      // 'typescript/no-restricted-imports': 'off',
      // 'typescript/no-shadow': 'error',
      // 'typescript/no-untyped-public-signature': 'off',
      // 'typescript/no-unused-expressions': 'error',
      // 'typescript/no-unused-vars': 'warn',
      // 'typescript/no-use-before-define': ['error']
      // 'typescript/no-useless-constructor': 'error',
      // 'typescript/prefer-readonlysemi': 'off',
      // 'typescript/no-unused-private-class-members': 'warn',
    },
  };
}
