import type { OxlintConfig } from 'oxlint';
import type { Context } from '../lib/Context.ts';

export function vitest(_ctx: Context): OxlintConfig {
  return {
    plugins: ['vitest'],
    rules: {
      'vitest/consistent-test-filename': ['warn', { allTestPattern: '__tests__', pattern: '.*\\.spec\\.tsx?$' }],
      'vitest/consistent-test-it': ['warn', { fn: 'it', withinDescribe: 'it' }],
      'vitest/consistent-vitest-vi': 'warn',
      'vitest/expect-expect': 'warn',
      'vitest/max-expects': 'off',
      'vitest/max-nested-describe': ['error', { max: 3 }],
      'vitest/no-alias-methods': 'warn',
      'vitest/no-commented-out-tests': 'warn',
      'vitest/no-conditional-expect': 'error',
      'vitest/no-conditional-in-test': 'error',
      'vitest/no-conditional-tests': 'error',
      'vitest/no-disabled-tests': 'error',
      'vitest/no-duplicate-hooks': 'error',
      'vitest/no-focused-tests': 'error',
      'vitest/no-hooks': 'off',
      'vitest/no-identical-title': 'error',
      'vitest/no-import-node-test': 'error',
      'vitest/no-importing-vitest-globals': 'off',
      'vitest/no-interpolation-in-snapshots': 'warn',
      'vitest/no-large-snapshots': 'warn',
      'vitest/no-mocks-import': 'warn',
      'vitest/no-restricted-matchers': 'off',
      'vitest/no-restricted-vi-methods': 'off',
      'vitest/no-standalone-expect': 'warn',
      'vitest/no-test-prefixes': 'error',
      'vitest/no-test-return-statement': 'error',
      'vitest/no-unneeded-async-expect-function': 'warn',
      'vitest/prefer-called-once': 'warn',
      'vitest/prefer-called-times': 'off',
      'vitest/prefer-called-with': 'warn',
      'vitest/prefer-comparison-matcher': 'warn',
      'vitest/prefer-describe-function-title': 'warn',
      'vitest/prefer-each': 'warn',
      'vitest/prefer-equality-matcher': 'warn',
      'vitest/prefer-expect-assertions': 'off',
      'vitest/prefer-expect-resolves': 'warn',
      'vitest/prefer-hooks-in-order': 'warn',
      'vitest/prefer-hooks-on-top': 'warn',
      'vitest/prefer-importing-vitest-globals': 'off',
      'vitest/prefer-lowercase-title': 'off',
      'vitest/prefer-mock-promise-shorthand': 'warn',
      'vitest/prefer-mock-return-shorthand': 'warn',
      'vitest/prefer-snapshot-hint': 'warn',
      'vitest/prefer-spy-on': 'warn',
      'vitest/prefer-strict-boolean-matchers': 'off',
      'vitest/prefer-strict-equal': 'off',
      'vitest/prefer-to-be': 'warn',
      'vitest/prefer-to-be-falsy': 'off',
      'vitest/prefer-to-be-object': 'warn',
      'vitest/prefer-to-be-truthy': 'off',
      'vitest/prefer-to-contain': 'warn',
      'vitest/prefer-to-have-length': 'warn',
      'vitest/prefer-todo': 'warn',
      'vitest/require-hook': 'off',
      'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
      'vitest/require-mock-type-parameters': 'off',
      'vitest/require-to-throw-message': 'warn',
      'vitest/require-top-level-describe': 'off',
      'vitest/valid-describe-callback': 'warn',
      'vitest/valid-expect': 'warn',
      'vitest/valid-expect-in-promise': 'warn',
      'vitest/valid-title': 'warn',
      'vitest/warn-todo': 'warn',

      // Unsupported
      // 'vitest/prefer-vi-mocked': 'warn',
    },
  };
}
