import type { OxlintConfig } from 'oxlint';
import type { Context } from '../lib/Context.ts';

export function base(ctx: Context): OxlintConfig {
  return {
    plugins: ['oxc', 'eslint'],
    rules: {
      'accessor-pairs': 'warn',
      'array-callback-return': 'error',
      'arrow-body-style': 'off',
      'capitalized-comments': 'off',
      'class-methods-use-this': 'off',
      'complexity': ['error', 14],
      'constructor-super': ctx.ts(),
      'curly': 'off',
      'default-case-last': 'error',
      'default-case': 'off',
      'default-param-last': 'warn',
      'eqeqeq': ['error', 'smart'],
      'for-direction': 'error',
      'func-name-matching': 'error',
      'func-names': 'error',
      'func-style': 'off',
      'getter-return': ['error', { allowImplicit: true }],
      'guard-for-in': 'error',
      'id-denylist': 'off',
      'id-length': 'off',
      'id-match': 'off',
      'logical-assignment-operators': 'warn',
      'max-classes-per-file': 'off',
      'max-depth': ['error', 4],
      'max-lines-per-function': ['warn', ctx.strictOr(100, 150)],
      'max-lines': [
        'error',
        {
          max: ctx.strictOr(500, 999),
          skipBlankLines: false,
          skipComments: false,
        },
      ],
      'max-nested-callbacks': ['error', 3],
      'max-params': ['error', ctx.strictOr(3, 4)],
      'max-statements': 'off', // readability is controlled by `max-lines-per-function`.
      'new-cap': 'off',
      'no-alert': 'error',
      'no-array-constructor': 'error',
      'no-await-in-loop': 'error',
      'no-bitwise': 'off',
      'no-caller': 'error',
      'no-case-declarations': 'warn',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': ctx.ts(),
      'no-constant-binary-expression': 'warn',
      'no-constant-condition': 'error',
      'no-constructor-return': 'error',
      'no-continue': 'off',
      'no-debugger': 'error',
      'no-delete-var': ctx.ts(),
      'no-dupe-class-members': ctx.ts(),
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': ctx.ts(),
      'no-duplicate-imports': 'warn',
      'no-else-return': 'off',
      'no-empty-function': 'off', // useless
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'warn',
      'no-empty': 'warn',
      'no-eq-null': 'off', // covered by eqeqeq smart.
      'no-eval': 'error',
      'no-ex-assign': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': ctx.ts(),
      'no-global-assign': 'error',
      'no-implied-eval': 'error',
      'no-implicit-coercion': 'warn',
      'no-import-assign': ctx.ts(),
      'no-inline-comments': 'off',
      'no-inner-declarations': 'error',
      'no-irregular-whitespace': 'error',
      'no-iterator': 'error',
      'no-lonely-if': 'warn',
      'no-loop-func': 'error',
      'no-loss-of-precision': 'error',
      'no-magic-numbers': 'off',
      'no-multi-assign': 'error',
      'no-multi-str': 'warn',
      'no-negated-condition': 'off',
      'no-nested-ternary': 'off',
      'no-new-func': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-new-wrappers': 'error',
      'no-new': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-object-constructor': 'error',
      'no-promise-executor-return': 'off',
      'no-proto': 'error',
      'no-prototype-builtins': 'off',
      'no-restricted-exports': 'off',
      'no-restricted-globals': ['error', { name: 'event', message: 'Use local parameter instead.' }],
      'no-restricted-properties': 'off',
      'no-return-assign': 'error',
      'no-script-url': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-shadow': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'warn',
      'no-ternary': 'off',
      'no-this-before-super': ctx.ts(),
      'no-throw-literal': 'warn',
      'no-unassigned-vars': ctx.strict('error'),
      'no-undef': ctx.ts(),
      'no-undefined': 'off',
      'no-underscore-dangle': 'off',
      'no-unmodified-loop-condition': 'error',
      'no-unneeded-ternary': 'warn',
      'no-unreachable-loop': 'error',
      'no-unreachable': ctx.ts(),
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': ctx.ts(),
      'no-unused-private-class-members': ctx.ts(),
      'no-unused-vars': ctx.ts(),
      'no-use-before-define': ctx.ts(),
      'no-useless-call': 'warn',
      'no-useless-catch': 'error',
      'no-useless-computed-key': 'warn',
      'no-useless-concat': 'warn',
      'no-useless-constructor': 'warn',
      'no-useless-escape': 'error',
      'no-useless-rename': 'warn',
      'no-useless-return': 'warn',
      'no-void': 'off', // used to mark intentionally ignored promises.
      'no-warning-comments': ['warn', { terms: ['fixme'], location: 'anywhere' }],
      'no-with': 'error',
      'object-shorthand': ['error', 'properties'],
      'one-var': ['error', { uninitialized: 'never', initialized: 'never' }],
      'operator-assignment': 'off',
      'prefer-arrow-callback': ['warn', { allowNamedFunctions: true, allowUnboundThis: true }],
      'prefer-destructuring': ['warn', { object: true, array: false }],
      'prefer-exponentiation-operator': 'warn',
      'prefer-named-capture-group': ctx.strict('warn'),
      'prefer-numeric-literals': 'error',
      'prefer-object-has-own': 'error',
      'prefer-object-spread': 'off',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'prefer-promise-reject-errors': 'warn',
      'radix': 'error',
      'require-await': 'error',
      'require-unicode-regexp': ctx.strict('warn'),
      'require-yield': 'error',
      'sort-imports': 'off',
      'sort-keys': 'off',
      'sort-vars': 'off',
      'symbol-description': 'error',
      'unicode-bom': 'off',
      'use-isnan': 'error',
      'valid-typeof': ctx.ts(),
      'yoda': 'error',
      'no-async-promise-executor': 'error',
      'grouped-accessor-pairs': 'warn',
      'no-extra-boolean-cast': 'warn',
      'no-param-reassign': 'error',
      'no-plusplus': ['warn', { allowForLoopAfterthoughts: true }],
      'no-console': ctx.strict('error'),
      'preserve-caught-error': ['warn', { requireCatchParameter: true }],
      'init-declarations': ctx.strict('error'),
      'no-restricted-imports': 'off',
      'no-unused-expressions': 'error',
      'no-unexpected-multiline': 'error',
      'no-useless-assignment': 'error',

      /* Variables */
      'block-scoped-var': 'off', // we enforces block scoping with `no-var` and `prefer-const`.
      'no-implicit-globals': 'off', // we enforce block scoping with `no-var` and `prefer-const`.
      'no-lone-blocks': 'off', // we enforce block scoping with `no-var` and `prefer-const`.
      'no-var': 'error',
      'prefer-const': 'warn',
      'vars-on-top': 'error',

      /* Labels */
      'no-labels': 'error',
      'no-extra-label': 'off', // we do not allow labels `no-labels`.
      'no-label-var': 'off', // we do not allow labels `no-labels`.
      'no-unused-labels': 'off', // we do not allow labels `no-labels`.
      'no-redeclare': 'off', // we do not allow labels `no-labels`.

      /* Regular Expressions */
      'no-control-regex': 'warn',
      'no-div-regex': 'error',
      'no-invalid-regexp': ctx.regex(),
      'no-useless-backreference': ctx.regex(),
      'no-misleading-character-class': ['error', { allowEscape: true }],
      'no-regex-spaces': 'error',
      'prefer-regex-literals': ['warn', { disallowRedundantWrapping: true }],
      'no-empty-character-class': ctx.regex(),

      'oxc/approx-constant': 'warn',
      'oxc/bad-array-method-on-arguments': 'error',
      'oxc/bad-bitwise-operator': 'warn',
      'oxc/bad-char-at-comparison': 'error',
      'oxc/bad-comparison-sequence': 'error',
      'oxc/bad-match-all-arg': 'error',
      'oxc/bad-min-max-func': 'error',
      'oxc/bad-object-literal-comparison': 'error',
      'oxc/bad-replace-all-arg': 'error',
      'oxc/branches-sharing-code': 'warn',
      'oxc/const-comparisons': 'error',
      'oxc/double-comparisons': 'error',
      'oxc/erasing-op': 'error',
      'oxc/misrefactored-assign-op': 'warn',
      'oxc/missing-throw': 'error',
      'oxc/no-accumulating-spread': 'warn',
      'oxc/no-async-await': 'off',
      'oxc/no-async-endpoint-handlers': 'warn',
      'oxc/no-barrel-file': 'off',
      'oxc/no-const-enum': 'off',
      'oxc/no-map-spread': ctx.strict('warn'),
      'oxc/no-optional-chaining': 'off',
      'oxc/no-rest-spread-properties': 'off',
      'oxc/no-this-in-exported-function': 'warn',
      'oxc/number-arg-out-of-range': 'error',
      'oxc/only-used-in-recursion': 'error',
      'oxc/uninvoked-array-callback': 'error',
    },
  };
}
