import type { OxlintConfig } from 'oxlint';
import type { Context } from '../lib/Context.ts';

export function jest(_ctx: Context): OxlintConfig {
  return {
    plugins: ['jest'],
    rules: {
      'jest/consistent-test-it': ['warn', { fn: 'it', withinDescribe: 'it' }],
      'jest/expect-expect': 'warn',
      'jest/max-expects': 'off',
      'jest/max-nested-describe': ['error', { max: 2 }],
      'jest/no-alias-methods': 'warn',
      'jest/no-commented-out-tests': 'warn',
      'jest/no-conditional-expect': 'error',
      'jest/no-conditional-in-test': 'error',
      'jest/no-confusing-set-timeout': 'error',
      'jest/no-deprecated-functions': 'warn',
      'jest/no-disabled-tests': 'error',
      'jest/no-done-callback': 'error',
      'jest/no-duplicate-hooks': 'error',
      'jest/no-export': 'error',
      'jest/no-focused-tests': 'error',
      'jest/no-hooks': 'off',
      'jest/no-identical-title': 'error',
      'jest/no-interpolation-in-snapshots': 'warn',
      'jest/no-jasmine-globals': 'error',
      'jest/no-large-snapshots': 'warn',
      'jest/no-mocks-import': 'warn',
      'jest/no-restricted-jest-methods': 'off',
      'jest/no-restricted-matchers': 'off',
      'jest/no-standalone-expect': 'warn',
      'jest/no-test-prefixes': 'error',
      'jest/no-test-return-statement': 'error',
      'jest/no-unneeded-async-expect-function': 'warn',
      'jest/no-untyped-mock-factory': 'off',
      'jest/padding-around-after-all-blocks': 'off',
      'jest/padding-around-test-blocks': 'off',
      'jest/prefer-called-with': 'warn',
      'jest/prefer-comparison-matcher': 'warn',
      'jest/prefer-each': 'warn',
      'jest/prefer-ending-with-an-expect': 'off',
      'jest/prefer-equality-matcher': 'warn',
      'jest/prefer-expect-assertions': 'off',
      'jest/prefer-expect-resolves': 'warn',
      'jest/prefer-hooks-in-order': 'warn',
      'jest/prefer-hooks-on-top': 'warn',
      'jest/prefer-importing-jest-globals': 'off',
      'jest/prefer-jest-mocked': 'warn',
      'jest/prefer-lowercase-title': 'off',
      'jest/prefer-mock-promise-shorthand': 'warn',
      'jest/prefer-mock-return-shorthand': 'warn',
      'jest/prefer-snapshot-hint': 'warn',
      'jest/prefer-spy-on': 'warn',
      'jest/prefer-strict-equal': 'off',
      'jest/prefer-to-be': 'warn',
      'jest/prefer-to-contain': 'warn',
      'jest/prefer-to-have-been-called': 'warn',
      'jest/prefer-to-have-been-called-times': 'off',
      'jest/prefer-to-have-length': 'warn',
      'jest/prefer-todo': 'warn',
      'jest/require-hook': 'off',
      'jest/require-to-throw-message': 'warn',
      'jest/require-top-level-describe': 'off',
      'jest/valid-describe-callback': 'warn',
      'jest/valid-expect': 'warn',
      'jest/valid-expect-in-promise': 'warn',
      'jest/valid-title': 'off',
    },
  };
}
