import type { OxlintConfig } from 'oxlint';
import type { Context } from '../lib/Context.ts';

const classComponent = 'off';
export function react(ctx: Context): OxlintConfig {
  return {
    plugins: ['react', 'react-perf', 'jsx-a11y'],
    rules: {
      'react/button-has-type': 'off', // buggy
      'react/capitalized-calls': 'off',
      'react/checked-requires-onchange-or-readonly': 'warn',
      'react/display-name': 'warn',
      'react/error-boundaries': 'error',
      'react/exhaustive-deps': 'warn',
      'react/exhaustive-effect-dependencies': 'off',
      'react/forbid-component-props': 'off',
      'react/forbid-dom-props': 'off',
      'react/forbid-elements': 'off',
      'react/forward-ref-uses-ref': 'error',
      'react/function-component-definition': 'off',
      'react/globals': 'error',
      'react/hook-use-state': 'warn',
      'react/hooks': 'off',
      'react/iframe-missing-sandbox': 'warn',
      'react/immutability': 'error',
      'react/incompatible-library': 'warn',
      'react/invariant': 'off',
      'react/jsx-boolean-value': 'warn',
      'react/jsx-curly-brace-presence': 'warn',
      'react/jsx-filename-extension': 'off',
      'react/jsx-fragments': 'warn',
      'react/jsx-handler-names': 'warn',
      'react/jsx-key': 'error',
      'react/jsx-max-depth': 'off',
      'react/jsx-no-comment-textnodes': 'warn',
      'react/jsx-no-constructed-context-values': 'warn',
      'react/jsx-no-duplicate-props': 'error',
      'react/jsx-no-literals': 'off',
      'react/jsx-no-script-url': 'warn',
      'react/jsx-no-target-blank': 'warn',
      'react/jsx-no-undef': ctx.ts(),
      'react/jsx-no-useless-fragment': 'warn',
      'react/jsx-pascal-case': 'error',
      'react/jsx-props-no-spread-multi': 'error',
      'react/jsx-props-no-spreading': 'off',
      'react/memo-dependencies': 'off',
      'react/no-array-index-key': 'warn',
      'react/no-children-prop': 'warn',
      'react/no-clone-element': 'warn',
      'react/no-danger-with-children': 'error',
      'react/no-danger': ctx.strict('warn'),
      'react/no-deriving-state-in-effects': 'off',
      'react/no-did-mount-set-state': classComponent,
      'react/no-did-update-set-state': classComponent,
      'react/no-direct-mutation-state': classComponent,
      'react/no-find-dom-node': classComponent,
      'react/no-is-mounted': classComponent,
      'react/no-multi-comp': 'off',
      'react/no-namespace': 'error',
      'react/no-object-type-as-default-prop': 'warn',
      'react/no-react-children': 'warn',
      'react/no-redundant-should-component-update': classComponent,
      'react/no-render-return-value': 'error',
      'react/no-set-state': classComponent,
      'react/no-string-refs': classComponent,
      'react/no-this-in-sfc': 'warn',
      'react/no-unescaped-entities': 'warn',
      'react/no-unknown-property': 'warn',
      'react/no-unsafe': classComponent,
      'react/no-unstable-nested-components': 'off',
      'react/no-will-update-set-state': classComponent,
      'react/only-export-components': [
        'warn',
        ctx.matchModule(
          'nextjs',
          {
            allowExportNames: [
              // https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config
              'experimental_ppr',
              'dynamic',
              'dynamicParams',
              'revalidate',
              'fetchCache',
              'runtime',
              'preferredRegion',
              'maxDuration',
              // https://nextjs.org/docs/app/api-reference/functions/generate-metadata
              'metadata',
              'generateMetadata',
              // https://nextjs.org/docs/app/api-reference/functions/generate-viewport
              'viewport',
              'generateViewport',
              // https://nextjs.org/docs/app/api-reference/functions/generate-image-metadata
              'generateImageMetadata',
              // https://nextjs.org/docs/app/api-reference/functions/generate-sitemaps
              'generateSitemaps',
              // https://nextjs.org/docs/app/api-reference/functions/generate-static-params
              'generateStaticParams',
            ],
          },
          { allowConstantExport: true },
        ),
      ],
      'react/prefer-es6-class': classComponent,
      'react/prefer-function-component': 'error',
      'react/preserve-manual-memoization': 'error',
      'react/purity': 'error',
      'react/react-in-jsx-scope': 'off',
      'react/refs': 'error',
      'react/require-render-return': classComponent,
      'react/rule-suppression': 'off',
      'react/rules-of-hooks': 'error',
      'react/self-closing-comp': 'warn',
      'react/set-state-in-effect': ctx.strict('error'),
      'react/set-state-in-render': 'error',
      'react/state-in-constructor': 'warn',
      'react/static-components': 'error',
      'react/style-prop-object': 'warn',
      'react/syntax': 'off',
      'react/todo': 'off',
      'react/unsupported-syntax': 'warn',
      'react/use-memo': 'error',
      'react/void-dom-elements-no-children': 'error',
      'react/void-use-memo': 'warn',
      'react-perf/jsx-no-jsx-as-prop': 'off',
      'react-perf/jsx-no-new-array-as-prop': 'off',
      'react-perf/jsx-no-new-function-as-prop': 'off',
      'react-perf/jsx-no-new-object-as-prop': 'off',

      'jsx-a11y/alt-text': 'warn',
      'jsx-a11y/anchor-ambiguous-text': 'warn',
      'jsx-a11y/anchor-has-content': 'warn',
      'jsx-a11y/anchor-is-valid': 'warn',
      'jsx-a11y/aria-activedescendant-has-tabindex': 'warn',
      'jsx-a11y/aria-props': 'warn',
      'jsx-a11y/aria-proptypes': 'warn',
      'jsx-a11y/aria-role': 'warn',
      'jsx-a11y/aria-unsupported-elements': 'warn',
      'jsx-a11y/autocomplete-valid': 'warn',
      'jsx-a11y/click-events-have-key-events': 'warn',
      'jsx-a11y/control-has-associated-label': 'warn',
      'jsx-a11y/heading-has-content': 'warn',
      'jsx-a11y/html-has-lang': 'warn',
      'jsx-a11y/iframe-has-title': 'warn',
      'jsx-a11y/img-redundant-alt': 'warn',
      'jsx-a11y/interactive-supports-focus': 'warn',
      'jsx-a11y/label-has-associated-control': 'warn',
      'jsx-a11y/lang': 'warn',
      'jsx-a11y/media-has-caption': 'warn',
      'jsx-a11y/mouse-events-have-key-events': 'warn',
      'jsx-a11y/no-access-key': 'warn',
      'jsx-a11y/no-aria-hidden-on-focusable': 'warn',
      'jsx-a11y/no-autofocus': 'warn',
      'jsx-a11y/no-distracting-elements': 'warn',
      'jsx-a11y/no-interactive-element-to-noninteractive-role': 'warn',
      'jsx-a11y/no-noninteractive-element-interactions': 'warn',
      'jsx-a11y/no-noninteractive-element-to-interactive-role': 'warn',
      'jsx-a11y/no-noninteractive-tabindex': 'warn',
      'jsx-a11y/no-redundant-roles': 'warn',
      'jsx-a11y/no-static-element-interactions': 'warn',
      'jsx-a11y/prefer-tag-over-role': 'warn',
      'jsx-a11y/role-has-required-aria-props': 'warn',
      'jsx-a11y/role-supports-aria-props': 'warn',
      'jsx-a11y/scope': 'warn',
      'jsx-a11y/tabindex-no-positive': 'warn',
    },
  };
}
