import type { OxlintConfig } from 'oxlint';
import type { Context } from '../lib/Context.ts';

export function typescript(ctx: Context): OxlintConfig {
  return {
    plugins: ['typescript'],
    rules: {
      'typescript/adjacent-overload-signatures': 'error',
      'typescript/array-type': 'warn',
      'typescript/await-thenable': ctx.typeAware('error'),
      'typescript/ban-ts-comment': ctx.strict([
        'error',
        {
          'ts-expect-error': 'allow-with-description',
          'ts-ignore': 'allow-with-description',
          'ts-nocheck': 'allow-with-description',
          'ts-check': 'allow-with-description',
        },
      ]),
      'typescript/ban-tslint-comment': 'off', // tslint is deprecated.
      'typescript/ban-types': 'off', // superseded by no-restricted-types / no-wrapper-object-types / no-unsafe-function-type.
      'typescript/class-literal-property-style': ['warn', 'getters'],
      'typescript/consistent-generic-constructors': ['warn', 'constructor'],
      'typescript/consistent-indexed-object-style': 'off',
      'typescript/consistent-return': 'off',
      'typescript/consistent-type-assertions': ['warn', { assertionStyle: 'as', objectLiteralTypeAssertions: 'allow-as-parameter' }],
      'typescript/consistent-type-definitions': ['warn', 'interface'],
      'typescript/consistent-type-exports': ctx.typeAware('warn'),
      'typescript/consistent-type-imports': [
        'warn',
        {
          prefer: 'type-imports',
          disallowTypeAnnotations: false,
          fixStyle: 'inline-type-imports',
        },
      ], // import/consistent-type-specifier-style?
      'typescript/dot-notation': ctx.typeAware([
        'warn',
        {
          allowPrivateClassPropertyAccess: false,
          allowProtectedClassPropertyAccess: false,
          allowIndexSignaturePropertyAccess: true,
        },
      ]),
      'typescript/explicit-function-return-type': 'off',
      'typescript/explicit-member-accessibility': 'off',
      'typescript/explicit-module-boundary-types': ctx.strict('error'),
      'typescript/method-signature-style': ['warn', 'property'],
      'typescript/no-array-delete': ctx.typeAware('error'),
      'typescript/no-base-to-string': ctx.typeAware('error'),
      'typescript/no-confusing-non-null-assertion': 'error',
      'typescript/no-confusing-void-expression': 'off',
      'typescript/no-deprecated': ctx.typeAware('error'),
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-duplicate-type-constituents': ctx.typeAware('warn'),
      'typescript/no-dynamic-delete': 'error',
      'typescript/no-empty-interface': 'off', // covered by no-empty-object-type.
      'typescript/no-empty-object-type': ['warn', { allowInterfaces: 'with-single-extends' }],
      'typescript/no-explicit-any': 'off', // tsc already does this.
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-extraneous-class': ['warn', { allowWithDecorator: true }],
      'typescript/no-floating-promises': ctx.typeAware(['error', { ignoreVoid: true }]),
      'typescript/no-for-in-array': ctx.typeAware('error'),
      'typescript/no-implied-eval': ctx.typeAware('error'),
      'typescript/no-import-type-side-effects': 'off', // import/no-import-type-side-effects covers this
      'typescript/no-inferrable-types': 'off',
      'typescript/no-invalid-void-type': 'error',
      'typescript/no-meaningless-void-operator': ctx.typeAware(['warn', { checkNever: false }]),
      'typescript/no-misused-new': 'error',
      'typescript/no-misused-promises': ctx.typeAware(['warn', { checksVoidReturn: { attributes: false } }]),
      'typescript/no-misused-spread': ctx.typeAware('error'),
      'typescript/no-mixed-enums': ctx.typeAware('error'),
      'typescript/no-namespace': ['error', { allowDeclarations: true, allowDefinitionFiles: true }],
      'typescript/no-non-null-asserted-nullish-coalescing': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-non-null-assertion': ctx.strictOr('warn', 'off'),
      'typescript/no-redundant-type-constituents': ctx.typeAware('warn'),
      'typescript/no-require-imports': ctx.esm('error'),
      'typescript/no-restricted-types': 'off',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-boolean-literal-compare': ctx.typeAware('error'),
      'typescript/no-unnecessary-condition': ctx.typeAware(['warn', { allowConstantLoopConditions: false }]),
      'typescript/no-unnecessary-parameter-property-assignment': 'warn',
      'typescript/no-unnecessary-qualifier': ctx.typeAware('error'),
      'typescript/no-unnecessary-template-expression': ctx.typeAware('warn'),
      'typescript/no-unnecessary-type-arguments': ctx.typeAware('error'),
      'typescript/no-unnecessary-type-assertion': ctx.typeAware('error'),
      'typescript/no-unnecessary-type-constraint': 'warn',
      'typescript/no-unnecessary-type-conversion': ctx.typeAware('error'),
      'typescript/no-unnecessary-type-parameters': ctx.typeAware('warn'),
      'typescript/no-unsafe-argument': ctx.typeAware('warn'),
      'typescript/no-unsafe-assignment': ctx.typeAware(ctx.strict('warn')),
      'typescript/no-unsafe-call': ctx.typeAware(ctx.strict('warn')),
      'typescript/no-unsafe-declaration-merging': 'warn',
      'typescript/no-unsafe-enum-comparison': ctx.typeAware('warn'),
      'typescript/no-unsafe-function-type': ctx.typeAware('warn'),
      'typescript/no-unsafe-member-access': ctx.typeAware(ctx.strict(['warn', { allowOptionalChaining: true }])),
      'typescript/no-unsafe-return': ctx.typeAware(ctx.strict('warn')),
      'typescript/no-unsafe-type-assertion': ctx.typeAware(ctx.strict('warn')),
      'typescript/no-unsafe-unary-minus': ctx.typeAware('error'),
      'typescript/no-useless-default-assignment': ctx.typeAware('warn'),
      'typescript/no-useless-empty-export': 'warn',
      'typescript/no-var-requires': 'off', // covered by no-require-imports.
      'typescript/no-wrapper-object-types': 'warn',
      'typescript/non-nullable-type-assertion-style': ctx.typeAware('warn'),
      'typescript/only-throw-error': ctx.typeAware(['warn', { allowRethrowing: true }]),
      'typescript/parameter-properties': 'off',
      'typescript/prefer-as-const': 'warn',
      'typescript/prefer-enum-initializers': ctx.strict('error'),
      'typescript/prefer-find': ctx.typeAware('warn'),
      'typescript/prefer-for-of': 'warn',
      'typescript/prefer-function-type': 'warn',
      'typescript/prefer-includes': ctx.typeAware('warn'),
      'typescript/prefer-literal-enum-member': ['error', { allowBitwiseExpressions: true }],
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/prefer-nullish-coalescing': ctx.typeAware([
        'warn',
        {
          ignoreConditionalTests: false,
          ignoreTernaryTests: false,
          ignoreMixedLogicalExpressions: true,
        },
      ]),
      'typescript/prefer-optional-chain': ctx.typeAware('warn'),
      'typescript/prefer-promise-reject-errors': ctx.typeAware('warn'),
      'typescript/prefer-readonly-parameter-types': 'off',
      'typescript/prefer-readonly': 'off',
      'typescript/prefer-reduce-type-parameter': ctx.typeAware('warn'),
      'typescript/prefer-regexp-exec': ctx.typeAware('warn'),
      'typescript/prefer-return-this-type': ctx.typeAware('warn'),
      'typescript/prefer-string-starts-ends-with': ctx.typeAware('warn'),
      'typescript/prefer-ts-expect-error': 'warn',
      'typescript/promise-function-async': 'off',
      'typescript/related-getter-setter-pairs': ctx.typeAware('error'),
      'typescript/require-array-sort-compare': ctx.typeAware(['error', { ignoreStringArrays: true }]),
      'typescript/require-await': ctx.typeAware('error'),
      'typescript/restrict-plus-operands': ctx.typeAware('warn'),
      'typescript/restrict-template-expressions': ctx.typeAware([
        'warn',
        { allowNumber: true, allowBoolean: false, allowAny: false, allowNullish: false, allowRegExp: false, allowNever: false },
      ]),
      'typescript/return-await': ctx.typeAware('error'),
      'typescript/strict-boolean-expressions': 'off',
      'typescript/strict-void-return': 'off',
      'typescript/switch-exhaustiveness-check': ctx.typeAware('error'),
      'typescript/triple-slash-reference': 'warn',
      'typescript/unbound-method': ctx.typeAware(['error', { ignoreStatic: true }]),
      'typescript/unified-signatures': 'error',
      'typescript/use-unknown-in-catch-callback-variable': ctx.typeAware('warn'),
    },
  };
}
