name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: Release
  cancel-in-progress: false

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
          registry-url: https://registry.npmjs.org

      - name: Check
        run: vp check

      - name: Test
        run: vp run -r test

      - name: Build
        run: vp run -r build

      - name: Release
        run: vp run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
